version: '3.5'

services:

# ==============> Database <=============
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /data/postgres
    volumes:
       - /Users/chuanvo/Documents/aptech/demo-micro-service/demo-microservice/data:/data/postgres
       - /Users/chuanvo/Documents/aptech/demo-micro-service/demo-microservice/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5438:5432"
    networks:
      - postgres
    restart: unless-stopped
  
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

# ==============> Front-end <=============
  store-front-end:
    image: chuanvo/store-front-end
    environment:
      USER_MANAGERMENT_SERVER_HOST: 'store-user-management'
      USER_MANAGERMENT_SERVER_PORT: 4000
      PRODUCT_MANAGERMENT_SERVER_HOST: 'store-product-management'
      PRODUCT_MANAGERMENT_SERVER_PORT: 4001
    ports:
      - "3000:3000"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

# ==============> User management <=============
  store-user-management:
    image: chuanvo/store-user-management
    environment:
      PGSQL_HOST: 'postgres'
      PGSQL_PORT: 5432
    ports:
      - "4000:4000"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

# ==============> Product management <=============
  store-product-management:
    image: chuanvo/store-product-management
    environment:
      PGSQL_HOST: 'postgres'
      PGSQL_PORT: 5432
    ports:
      - "4001:4001"
    networks:
      - postgres
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: